# Generated by Django 6.0.2 on 2026-02-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('step', models.CharField(default='start', max_length=50)),
                ('selected_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
