# Generated by Django 6.0.2 on 2026-02-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='selected_location',
            new_name='selected_area',
        ),
        migrations.AddField(
            model_name='usersession',
            name='selected_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
