# Generated by Django 6.0.2 on 2026-02-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_rename_selected_location_usersession_selected_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='selected_turf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
