# Generated by Django 6.0.2 on 2026-02-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_area_booking_alter_usersession_selected_slot_turf'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='selected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
