# Generated by Django 6.0.2 on 2026-03-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_booking_date_usersession_selected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
